[project]
name = "chatbot-sample"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "boto3>=1.35.56",
    "chainlit>=1.3.1",
    "langchain>=0.3.7",
    "langchain-aws>=0.2.7",
    "langgraph>=0.2.45",
]
